services:
  app:
    build: .
    container_name: alliance-basket-ui
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - alliance-basket

networks:
  alliance-basket:
    external: true
