services:
  app:
    build: .
    container_name: alliance_basket-ui
    ports:
      - "3000:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"

